dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  image_picker: ^1.0.4  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0